File "./typechecking/invalid/unbound_break.sk", line 2, characters 3-10:
Unexpected 'break' found outside a loop
1 | fun no1(): Int {
2 |   break 42
  |   ^^^^^^^^
3 | }
File "./typechecking/invalid/unbound_break.sk", line 6, characters 9-21:
Unexpected 'break' found outside a loop
4 |
5 | fun no2(): void {
6 |   while (break false) void
  |         ^^^^^^^^^^^^^
7 | }
File "./typechecking/invalid/unbound_break.sk", line 10, characters 17-29:
Unexpected 'break' found outside a loop
 8 |
 9 | fun no3(): void {
10 |   do void while (break false)
   |                 ^^^^^^^^^^^^^
11 | }
File "./typechecking/invalid/unbound_break.sk", line 14, characters 37-46:
Unexpected 'break' found outside a loop
12 |
13 | fun no4(): void {
14 |   for (_ in Vector[1, 2]) void else break void
   |                                     ^^^^^^^^^^
15 | }
File "./typechecking/invalid/unbound_break.sk", line 18, characters 24-33:
Unexpected 'break' found outside a loop
16 |
17 | fun no5(): void {
18 |   while (false) (() -> break void)()
   |                        ^^^^^^^^^^
19 | }
File "./typechecking/invalid/unbound_break.sk", line 24, characters 7-16:
Unexpected 'break' found outside a loop
22 |   while (false) {
23 |     async {
24 |       break void
   |       ^^^^^^^^^^
25 |     }
