File "tests/runtime/invalid/try_catch_return_2.sk", line 6, characters 12-23:
Forbidden use of 'return' inside a 'try ... catch'.
4 |       "Foo"
5 |     } catch {
6 |     | _ -> return "Bar"
  |            ^^^^^^^^^^^^
7 |     }
