File "tests/runtime/invalid/try_catch_continue_1.sk", line 6, characters 19-26:
Forbidden use of 'continue' inside a 'try ... catch'.
4 |     try {
5 |       !i = i + 1;
6 |       if (i == 0) continue
  |                   ^^^^^^^^
7 |     } catch {
