fun main(): void {
  try {
    return void
  } catch {
  | Exception _ -> void
  }
}
