class MyExn(x: Int) extends Exception

fun test(): void {
  vtry(
    () -> {
      throw MyExn(0)
    },
    exn ->
      exn match {
      | MyExn(x) if (x == 42) -> invariant_violation("FAIL")
      | e -> throw e
      }
    ,
  )
}

fun main(): void {
  print_raw(
    vtry(
      () -> {
        test();
        "FAIL"
      },
      exn ->
        exn match {
        | MyExn(x) if (x == 0) -> "Pass\n"
        | _ -> "Fail\n"
        }
      ,
    ),
  )
}
