File "tests/runtime/invalid/try_catch_continue_2.sk", line 7, characters 24-31:
Forbidden use of 'continue' inside a 'try ... catch'.
5 |       !i = i + 1;
6 |     } catch {
7 |     | _ -> if (i == 0) continue
  |                        ^^^^^^^^
8 |     }
